# Generated by Django 3.0 on 2021-08-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregYResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta1', models.CharField(max_length=200)),
                ('respuesta2', models.CharField(max_length=200)),
                ('respuesta3', models.CharField(max_length=200)),
                ('respuesta_correcta', models.CharField(max_length=200)),
                ('puntaje', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_categoria', to='categorias.Categoria')),
            ],
        ),
    ]
